sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t mar-kub/docker-latex-build .

script:
  - docker run -it mar-kub/docker-latex-build latex -v
  - docker run -it mar-kub/docker-latex-build latexmk -v
  - docker run -it mar-kub/docker-latex-build biber -v
  - docker run -it mar-kub/docker-latex-build pandoc -v